FROM nvidia/cuda:12.4.0-base-ubuntu22.04

# Install Python 3.11.5 and dependencies
RUN apt-get update && apt-get install -y \
    python3.11 \
    python3.11-distutils \
    python3.11-venv \
    python3-pip \
    build-essential \
    curl \
    && apt-get clean

# Install pip for Python 3.11
RUN curl https://bootstrap.pypa.io/get-pip.py | python3.11
# Set Python 3.11 as the default python version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1

# Install common Python packages (optional)
RUN python -m pip install --upgrade pip setuptools wheel

RUN apt-get update && apt-get install -y --no-install-recommends \
    x11-apps \
    libxxf86vm1 \
    libxkbcommon0 \
    libgl1 \
    libegl1 \
    libglib2.0-0 \
    libxi6 \
    htop \
    nano && apt-get clean && rm -rf /var/lib/apt/lists/*

# Setup working directory (will be mounted later on)
RUN mkdir /masterarbeit
WORKDIR /masterarbeit

# Permissions
RUN addgroup -gid 5002 container
RUN adduser --disabled-password --gecos '' --uid 5036 --gid 5002 container
USER container

# But we do need the requirements before
COPY setup/requirements_gpu.txt /requirements.txt
RUN  pip install --no-cache-dir -r /requirements.txt

ENV GPU_SERVER=1

CMD ["bash"]
