top_snippets = [
    "AeroDarts Co.",
    "Bullseye Dynamics",
    "Skyline Precision",
    "TargetWorks",
    "OrbitThrow Gear",
    "Falcon Sports",
    "SilverArrow",
    "Zenith Darts",
    "TrueFlight Co.",
    "EagleEye Supplies",
    "AeroDarts",
    "Bullseye Co.",
    "Skyline",
    "TargetWorks",
    "OrbitGear",
    "Falcon",
    "SilverArrow",
    "Zenith",
    "TrueFlight",
    "EagleEye",
    "DartWorks",
    "SkyDarts",
    "IronBull",
    "SteelAim",
    "BullSharp",
    "TrueMark",
    "ZenDarts",
    "FlightPro",
    "OrbitPro",
    "SharpEye",
    "FocusGear",
    "ArrowPoint",
    "HighMark",
    "PrimeFlight",
    "PrecisionPro",
    "Dartify",
    "BoomThrow",
    "ZingAim",
    "BullzUp",
    "FlyZap",
    "PokeCo",
    "ZappyDart",
    "SpinMark",
    "ChonkDarts",
    "FlimFlam",
    "ZapFlight",
    "PlunkPro",
    "TwistBull",
    "Pointo",
    "AimzCo",
    "BlammoDarts",
    "Thunkerz",
    "Boingo",
    "ZapBull",
    "DartSnax",
    "WobbleAim",
    "Flingz",
    "PointyCo",
    "Bullzo",
    "ThrowZapp",
    "ThunkCo",
    "ZapBoom",
    "PlinkDarts",
    "Flickerz",
    "BongoThrow",
    "Ploink!",
    "Dartos",
    "SnagAim",
    "SpindleZap",
    "PokeyBull",
    "BlasterDarts Unlimited",
    "ZapTarget Precision",
    "Boomerang Throw Co.",
    "BullzEye Champions",
    "IronTip Sports",
    "Skyline Throw Masters",
    "Dart Blasters Inc.",
    "Orbit Dartworks",
    "Falcon Aim Systems",
    "TrueFlight Pro Gear",
    "SilverArrow Darts",
    "Poke 'n Throw Co.",
    "ThunderDart Makers",
    "Bulls 'n Beyond",
    "SharpShooter's Guild",
    "Target Masters Co.",
    "Bullseye Throwers",
    "Iron Precision Gear",
    "HighMark Dartworks",
    "Thunder Flight Systems",
    "Steady Hands Co.",
    "Golden Aim Gear",
    "Dart Horizons",
    "Next-Level Darts",
    "Victory Dart Supply",
    "Red Ring Makers",
    "Elite Throwing Co.",
    "SkyBull Precision",
    "Sharper Marks Inc.",
    "Falcon Aim Pros",
    "Bullseye Bonanza",
    "Dartstorm Enterprises",
    "Throwtastic Co.",
    "Zapstrike Darts",
    "PewPew Precision",
    "FlightBlasters Inc.",
    "PointQuest Darts",
    "Bullzy Enterprises",
    "The Dart Box",
    "AimLab Innovations",
    "Sonic Sharp Darts",
    "Boomerang Bullseye",
    "ZingPoint Gear",
    "The Dart Pit",
    "FlyRight Co.",
    "ZapFlight Systems",
    "ArrowForce Industries",
    "DartVibe Creations",
    "WhizzBang Darts",
    "FlingMaster Inc.",
    "BlazeFly Darts",
    "Snappy Shots Co.",
    "TargetZap",
    "AirStrike Darts",
    "Flyer's Edge Co.",
    "PowerDart Provisions",
    "ThunderThrow Industries",
    "ZeroBull Dartworks",
    "WildFlight Enterprises",
    "PointBusters Co.",
]


bottom_snippets = [
    "Hit the Mark",
    "Aim True",
    "Play Bold",
    "Sharp Focus",
    "Take Flight",
    "Stay Centered",
    "Pure Precision",
    "Game On",
    "Strike True",
    "Nail It",
    "Focus",
    "Throw",
    "Play",
    "Hit",
    "Win",
    "Mark",
    "Fly",
    "Score",
    "Center",
    "Aim",
    "Fly",
    "Hit",
    "Score",
    "Win",
    "Focus",
    "Throw",
    "Bull",
    "Mark",
    "Play",
    "Point",
    "Edge",
    "True",
    "Sharp",
    "Darts",
    "Zap",
    "Boop",
    "Pop",
    "Fling",
    "Zap!",
    "Ding",
    "Whoop",
    "Spin",
    "Chonk",
    "Thunk",
    "Ping",
    "Dartz",
    "Yolo",
    "Bop",
    "Plonk",
    "Pow",
    "Zap!",
    "Pew",
    "Thunk",
    "Boop",
    "Wob",
    "Yow",
    "Zing",
    "Ping",
    "Clonk",
    "Thwap",
    "Spin",
    "Fwap",
    "Bop",
    "Yoink",
    "Plink",
    "Oof",
    "Ploop",
    "Fwoosh",
    "Zonk",
    "Aim for greatness!",
    "Every throw counts.",
    "Unleash your inner pro.",
    "Precision at every mark.",
    "Dart to the finish!",
    "Feel the bullseye.",
    "Strike with confidence.",
    "Fly true, hit strong.",
    "Built for champions.",
    "Engineered to win.",
    "The ultimate throw.",
    "Hit hard, aim sharp.",
    "Where focus meets skill.",
    "Stay steady, score big.",
    "Throw like a legend.",
    "Precision in every throw.",
    "Aim true, win big.",
    "Built for serious players.",
    "Unleash your best shot.",
    "Take aim, dominate.",
    "The path to perfection.",
    "Score higher, aim sharper.",
    "Hit the mark every time.",
    "From focus to finish.",
    "The art of precision.",
    "Step up your game.",
    "Power your passion.",
    "Focus. Throw. Win.",
    "Engineered for winners.",
    "Your aim, redefined.",
    "Bullseye Bound",
    "Throw Like a Rocket",
    "Target Lock",
    "Sonic Flight",
    "Aim for the Stars",
    "Dartastic!",
    "The Point of No Return",
    "Zap the Bullseye",
    "Precision Playground",
    "In the Zone",
    "Zero to Bullseye",
    "Take the Shot",
    "Unstoppable Dart",
    "Launch Mode",
    "Chase the Arrow",
    "Wild Flight",
    "Full Throttle Aim",
    "Strike Fast, Strike First",
    "Arrow Fury",
    "Hitting Hyperdrive",
    "Aim, Fire, Repeat",
    "Stay Sharp, Play Hard",
    "Zip Zap Boom!",
    "Zing Your Way to Victory",
    "Pop That Bullseye",
    "One Shot, One Bull",
    "Boom! Right On",
    "Fling 'Em All!",
    "Spin It, Win It",
    "Bullseye Buzz",
    "Crack the Mark",
    "It's Dart Time",
    "Smash the Board",
    "Zap to Victory",
    "Focus, Throw, Zing",
    "Hitting Hard, Hitting Fast",
    "Take Your Shot",
    "Blaze the Dart Trail",
    "Get in the Zone",
    "Victory in Flight",
]
