top_snippets = [
    "AeroDarts Co.",
    "Bullseye Dynamics",
    "Skyline Precision",
    "TargetWorks",
    "OrbitThrow Gear",
    "Falcon Sports",
    "SilverArrow",
    "Zenith Darts",
    "TrueFlight Co.",
    "EagleEye Supplies",
    "AeroDarts",
    "Bullseye Co.",
    "Skyline",
    "TargetWorks",
    "OrbitGear",
    "Falcon",
    "SilverArrow",
    "Zenith",
    "TrueFlight",
    "EagleEye",
    "DartWorks",
    "SkyDarts",
    "IronBull",
    "SteelAim",
    "BullSharp",
    "TrueMark",
    "ZenDarts",
    "FlightPro",
    "OrbitPro",
    "SharpEye",
    "FocusGear",
    "ArrowPoint",
    "HighMark",
    "PrimeFlight",
    "PrecisionPro",
    "Dartify",
    "BoomThrow",
    "ZingAim",
    "BullzUp",
    "FlyZap",
    "PokeCo",
    "ZappyDart",
    "SpinMark",
    "ChonkDarts",
    "FlimFlam",
    "ZapFlight",
    "PlunkPro",
    "TwistBull",
    "Pointo",
    "AimzCo",
    "BlammoDarts",
    "Thunkerz",
    "Boingo",
    "ZapBull",
    "DartSnax",
    "WobbleAim",
    "Flingz",
    "PointyCo",
    "Bullzo",
    "ThrowZapp",
    "ThunkCo",
    "ZapBoom",
    "PlinkDarts",
    "Flickerz",
    "BongoThrow",
    "Ploink!",
    "Dartos",
    "SnagAim",
    "SpindleZap",
    "PokeyBull",
    "BlasterDarts Unlimited",
    "ZapTarget Precision",
    "Boomerang Throw Co.",
    "BullzEye Champions",
    "IronTip Sports",
    "Skyline Throw Masters",
    "Dart Blasters Inc.",
    "Orbit Dartworks",
    "Falcon Aim Systems",
    "TrueFlight Pro Gear",
    "SilverArrow Darts",
    "Poke 'n Throw Co.",
    "ThunderDart Makers",
    "Bulls 'n Beyond",
    "SharpShooter's Guild",
    "Target Masters Co.",
    "Bullseye Throwers",
    "Iron Precision Gear",
    "HighMark Dartworks",
    "Thunder Flight Systems",
    "Steady Hands Co.",
    "Golden Aim Gear",
    "Dart Horizons",
    "Next-Level Darts",
    "Victory Dart Supply",
    "Red Ring Makers",
    "Elite Throwing Co.",
    "SkyBull Precision",
    "Sharper Marks Inc.",
    "Falcon Aim Pros",
]


bottom_snippets = [
    "Hit the Mark",
    "Aim True",
    "Play Bold",
    "Sharp Focus",
    "Take Flight",
    "Stay Centered",
    "Pure Precision",
    "Game On",
    "Strike True",
    "Nail It",
    "Focus",
    "Throw",
    "Play",
    "Hit",
    "Win",
    "Mark",
    "Fly",
    "Score",
    "Center",
    "Aim",
    "Fly",
    "Hit",
    "Score",
    "Win",
    "Focus",
    "Throw",
    "Bull",
    "Mark",
    "Play",
    "Point",
    "Edge",
    "True",
    "Sharp",
    "Darts",
    "Zap",
    "Boop",
    "Pop",
    "Fling",
    "Zap!",
    "Ding",
    "Whoop",
    "Spin",
    "Chonk",
    "Thunk",
    "Ping",
    "Dartz",
    "Yolo",
    "Bop",
    "Plonk",
    "Pow",
    "Zap!",
    "Pew",
    "Thunk",
    "Boop",
    "Wob",
    "Yow",
    "Zing",
    "Ping",
    "Clonk",
    "Thwap",
    "Spin",
    "Fwap",
    "Bop",
    "Yoink",
    "Plink",
    "Oof",
    "Ploop",
    "Fwoosh",
    "Zonk",
    "Aim for greatness!",
    "Every throw counts.",
    "Unleash your inner pro.",
    "Precision at every mark.",
    "Dart to the finish!",
    "Feel the bullseye.",
    "Strike with confidence.",
    "Fly true, hit strong.",
    "Built for champions.",
    "Engineered to win.",
    "The ultimate throw.",
    "Hit hard, aim sharp.",
    "Where focus meets skill.",
    "Stay steady, score big.",
    "Throw like a legend.",
    "Precision in every throw.",
    "Aim true, win big.",
    "Built for serious players.",
    "Unleash your best shot.",
    "Take aim, dominate.",
    "The path to perfection.",
    "Score higher, aim sharper.",
    "Hit the mark every time.",
    "From focus to finish.",
    "The art of precision.",
    "Step up your game.",
    "Power your passion.",
    "Focus. Throw. Win.",
    "Engineered for winners.",
    "Your aim, redefined.",
]
